name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: azurity/upromise/.github/workflows/c-cpp.yml@build
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: load packages
      uses: actions/download-artifact@v3
      with:
        name: packages
        path: packages
    - name: create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "packages/*"
